---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu 
    driver_config:
      box: ubuntu-16.04
      box_url: file://~/cookbooks/home_vbox_server/ubuntu-16.04-amd64.box
      password: vagrant1

suites:
  - name: default
    run_list:
      - recipe[home_vbox_server::default]
    attributes:
